const testCSVData = [
  [
    "id",
    "name",
    "description",
    "organization_link",
    "address",
    "postcode",
    "organization_website",
    "telephone",
    "email",
  ],
  [
    "dQ-t3O0htMs",
    "\nCamden High Street Public Conveniences\n",
    "Ladies' and gents' toilets, and baby changing facilities.",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=dQ-t3O0htMs&communitychannel=6-11",
    "Block A,211 Arlington Rd,London,NW1 7HD",
    "NW1 7HD",
    "http://www.camden.gov.uk/toilets",
    "",
    "operationsteam@camden.gov.uk",
  ],
  [
    "fts8h-k2vBM",
    "\nCamden Town Female Public Conveniences\n",
    "",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=fts8h-k2vBM&communitychannel=6-11",
    "Public Convenience,Parkway,London,NW1 7JY",
    "NW1 7JY",
    "https://beta.camden.gov.uk/public-toilets",
    "020 7974 4444",
    "operationsteam@camden.gov.uk",
  ],
  [
    "r2Sx3q6qRjk",
    "\n\n\n\nCamden Town Library\n",
    "Public library run by Camden Council. Collection includes books, audiobooks and digital content. Information about Council and other local services and organisations is available, including Community and Camden libraries noticeboards. Learning Centre provides internet access, public computers, scanning, printing/photocopying and self-service kiosks. Children's library with…",
    "https://cindex.camden.gov.uk/kb5/camden/cd/advice.page?id=r2Sx3q6qRjk",
    "Crowndale Centre,218 ,Eversholt Street,London,NW1 1BD",
    "NW1 1BD",
    "",
    "020 7974 4444",
    "libraries@camden.gov.uk",
  ],
  [
    "Ir7e0fUuv0Q",
    "\nCamden Town Male Public Conveniences\n",
    "",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=Ir7e0fUuv0Q&communitychannel=6-11",
    "Public Convenience,Camden High Street,London,NW1 0NS",
    "NW1 0NS",
    "https://beta.camden.gov.uk/public-toilets",
    "020 7974 4444",
    "operationsteam@camden.gov.uk",
  ],
  [
    "hSWES3Uubr4",
    "\nCommunity Toilet Scheme\n",
    "Local retailers and other services make toilets accessible to both customers and other members of the public. Proprietors reserve the right of admission in exceptional circumstances. Toilet locations are on the website listed here.",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=hSWES3Uubr4&communitychannel=6-11",
    "2nd Floor,Block A,211 ,Arlington Rd,London,NW1 7HD",
    "NW1 7HD",
    "http://www.camden.gov.uk/cts",
    "",
    "publictoilets@camden.gov.uk",
  ],
  [
    "6Vp-wgcpnpw",
    "\nCrowndale Centre Public Conveniences\n",
    "Ladies', gents' and disabled people's toilets.",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=6Vp-wgcpnpw&communitychannel=6-11",
    "Crowndale Centre,218 ,Eversholt Street,London,NW1 1BD",
    "NW1 1BD",
    "http://www.camden.gov.uk/toilets",
    "020 7974 1564",
    "",
  ],
  [
    "8M-X8lvSynQ",
    "\nEast Heath Road Public Conveniences\n",
    "Ladies, Gents and wheelchair accessible toilets.",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=8M-X8lvSynQ&communitychannel=6-11",
    "City of London (Open Spaces),Heathfield House,432 ,Archway Road,London,N6 4JH",
    "N6 4JH",
    "http://www.cityoflondon.gov.uk/openspaces",
    "",
    "hampstead.heath@cityoflondon.gov.uk",
  ],
  [
    "b44jUr4pahI",
    "\nEuston Station Public Conveniences\n",
    "Ladies', gents' and disabled people's toilets and baby-change room.",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=b44jUr4pahI&communitychannel=6-11",
    "Euston Station,Euston Road,London,NW1 2RT",
    "NW1 2RT",
    "http://www.networkrail.co.uk/aspx/819.aspx",
    "",
    "",
  ],
  [
    "Qv1hpMjNnzU",
    "\nHampstead Heath Public Conveniences\n",
    "Toilets including toilets for disabled people. Accessible toilets are located at Parliament Hill Staff Yard, at the athletics track, at Millfield Lane, at the Vale of Health, at Kenwood House, at Golders Hill Park Cafe, at Golders Hill Park Zoo and at the Heath Extension.…",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=Qv1hpMjNnzU&communitychannel=6-11",
    "Heathfield House,432 ,Archway Road,London,N6 4JH",
    "N6 4JH",
    "http://www.cityoflondon.gov.uk/hampstead",
    "020 7332 3322",
    "hampstead.heath@cityoflondon.gov.uk",
  ],
  [
    "r2Sx3q6qRjk",
    "\n\n\n\nHighgate Library\n",
    "Public library run by Camden Council. From April 2015 the services is delivered by library volunteers and a paid officer. Collection includes books, talking books, newspapers, periodicals and leaflets. Also available, information about Council and other local services and organisations.  Facilities include a photocopier and neighbourhood…",
    "https://cindex.camden.gov.uk/kb5/camden/cd/advice.page?id=r2Sx3q6qRjk",
    "Chester Road,London,N19 5DH",
    "N19 5DH",
    "http://www.camden.gov.uk/highgatelibrary",
    "020 7974 4444",
    "libraries@camden.gov.uk",
  ],
  [
    "KG4WwGuub6M",
    "\nHighgate Road Public Conveniences\n",
    "Ladies', gents' and disabled people's toilets.",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=KG4WwGuub6M&communitychannel=6-11",
    "Heathfield House,432 ,Archway Road,London,N6 4JH",
    "N6 4JH",
    "http://www.cityoflondon.gov.uk/openspaces",
    "020 7332 3322, 020 7332 3773",
    "",
  ],
  [
    "r2Sx3q6qRjk",
    "\n\n\n\nHolborn Library\n",
    "Public library run by Camden Council. Collection includes books, talking books, CDs and DVDs, newspapers and periodicals. Information about Council and other local services and organisations. Photocopier and neighbourhood noticeboard. Children's library with Baby Bounce session for Under 2s Wed 11-11.30am term time only. Learning…",
    "https://cindex.camden.gov.uk/kb5/camden/cd/advice.page?id=r2Sx3q6qRjk",
    "32-38, ,Theobalds Road,London,WC1X 8PA",
    "WC1X 8PA",
    "http://www.camden.gov.uk/holbornlibrary",
    "020 7974 4444",
    "libraries@camden.gov.uk",
  ],
  [
    "JGVc9PeM9bU",
    "\nKentish Town Library\n",
    "Public library run by Camden Council. Collection includes books, talking books,  self-help leaflets. Information about Council and other local services and organisations. Photocopier and neighbourhood noticeboard. Children's library with Rhyme Time sessions for under 4s Mon 10.30am-11am and Wed 10.30am-11am in term time. Free internet…",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=JGVc9PeM9bU&communitychannel=6-11",
    "262-266, ,Kentish Town Road,London,NW5 2AA",
    "NW5 2AA",
    "http://www.camden.gov.uk/kentishtownlibrary",
    "020 7974 4444",
    "libraries@camden.gov.uk",
  ],
  [
    "QPSeKHzyxic",
    "\nKenwood House Public Conveniences\n",
    "Toilets open to the public as part of the park and historic Kenwood House.",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=QPSeKHzyxic&communitychannel=6-11",
    "Kenwood House,Hampstead Lane,London,NW3 7JR",
    "NW3 7JR",
    "",
    "020 8348 1286",
    "",
  ],
  [
    "r2Sx3q6qRjk",
    "\n\n\n\nKilburn Library Centre\n",
    "Public library run by Camden Council. Collection includes books, talking books, information about Camden Council and other local services and organisations. Internet access, printing and photocopying facilities, and free Wi-Fi are available. There are also events for both adults and childen, including Rhyme Times, reading…",
    "https://cindex.camden.gov.uk/kb5/camden/cd/advice.page?id=r2Sx3q6qRjk",
    "12 - 22 ,Kilburn High Road,London,NW6 5UH",
    "NW6 5UH",
    "http://www.camden.gov.uk/kilburnlibrary",
    "020 7974 4444",
    "libraries@camden.gov.uk",
  ],
  [
    "zjCNUz2qhDk",
    "\nLincolns Inn Fields Public Conveniences\n",
    "Ladies' and gents' toilets, and baby changing facilities.",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=zjCNUz2qhDk&communitychannel=6-11",
    "Block A,211 ,Arlington Rd,London,NW1 7HD",
    "NW1 7HD",
    "http://www.camden.gov.uk/toilets",
    "",
    "operationsteam@camden.gov.uk",
  ],
  [
    "vGQkAVdtfvI",
    "\nMillfield Lane Public Conveniences\n",
    "Ladies', gents' and disabled people's toilets.",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=vGQkAVdtfvI&communitychannel=6-11",
    "c/o Hampstead Heath Superintendent's Office,Heathfield House,432 ,Archway Road,London,N6 4JH",
    "N6 4JH",
    "http://www.cityoflondon.gov.uk/hampstead",
    "",
    "hampstead.heath@cityoflondon.gov.uk",
  ],
  [
    "Gk_DsXFyR6k",
    "\nNational Key Scheme for Toilets for Disabled People\n",
    "Toilets fitted with NKS locks in Camden include: Clerkenwell Road/Leather Lane Junction; High Holborn, near Holborn underground station; Russell Square; King's Cross Station, Platform 8; Euston Station by the ladies toilet; Corner of Chalton Street and Euston Road; Swiss Cottage Community Centre; at Parliament Hill…",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=Gk_DsXFyR6k&communitychannel=6-11",
    "12,City Forum,250 ,City Road,London,EC1V 8AF",
    "EC1V 8AF",
    "https://www.disabilityrightsuk.org/how-we-can-help/advice-and-information",
    "020 7250 3222",
    "",
  ],
  [
    "r2Sx3q6qRjk",
    "\n\n\n\nPancras Square Library\n",
    "Public library run by Camden Council. Collection includes books, talking books and self-help leaflets. Information about Council and other local services and organisations. Photocopier and neighbourhood noticeboard. Children's library with Rhyme Time session for under-5s Fri at 11-11.30am. Xbox and Playstation games. Jobzone with a…",
    "https://cindex.camden.gov.uk/kb5/camden/cd/advice.page?id=r2Sx3q6qRjk",
    "5 ,Pancras Square,London,N1C 4AG",
    "N1C 4AG",
    "https://www.camden.gov.uk/pancras-square-library",
    "020 7974 4444",
    "libraries@camden.gov.uk",
  ],
  [
    "bZIV4tJgbKA",
    "\nPond Square Public Conveniences\n",
    "Ladies', gents' and disabled peoples' toilets, and baby changing facilities.",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=bZIV4tJgbKA&communitychannel=6-11",
    "Block A,211 ,Arlington Rd,London,NW1 7HD",
    "NW1 7HD",
    "http://www.camden.gov.uk/toilets",
    "",
    "operationsteam@camden.gov.uk",
  ],
  [
    "a18WeIuydJs",
    "\nPublic Conveniences Service (Camden Council)\n",
    "Manages Camden Council's public toilets (all ladies' and gents').",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=a18WeIuydJs&communitychannel=6-11",
    "Block A,211 ,Arlington Rd,London,NW1 7HD",
    "NW1 7HD",
    "http://www.camden.gov.uk/toilets",
    "",
    "operationsteam@camden.gov.uk",
  ],
  [
    "r2Sx3q6qRjk",
    "\n\n\n\nQueens Crescent Library\n",
    "Queens Crescent Library is open for customers to browse and choose their own books, visit our children's library, and to use our public computers and our study spaces. You don’t need to book a computer in advance, computers are allocated on a first come, first served…",
    "https://cindex.camden.gov.uk/kb5/camden/cd/advice.page?id=r2Sx3q6qRjk",
    "165 ,Queens Crescent,London,NW5 4HH",
    "NW5 4HH",
    "http://www.camden.gov.uk/queenscrescentlibrary",
    "020 7974 4444",
    "libraries@camden.gov.uk",
  ],
  [
    "81RiAMe2pPQ",
    "\nQueens Crescent Public Conveniences\n",
    "Ladies', gents' and disabled people's toilets.",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=81RiAMe2pPQ&communitychannel=6-11",
    "Block A,Arlington Road Depot,211 ,Arlington Road,London,NW1 7HD",
    "NW1 7HD",
    "http://www.camden.gov.uk/toilets",
    "020 7974 4444",
    "operationsteam@camden.gov.uk",
  ],
  [
    "HUTxxcZlQF4",
    "\nSouth End Green Public Conveniences\n",
    "Ladies' and gents' toilets and baby changing facilities.",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=HUTxxcZlQF4&communitychannel=6-11",
    "Block A,211 ,Arlington Rd,London,NW1 7HD",
    "NW1 7HD",
    "http://www.camden.gov.uk/toilets",
    "",
    "operationsteam@camden.gov.uk",
  ],
  [
    "YCw02tAz59g",
    "\nSt Pancras International Station Public Conveniences\n",
    "Two sets of toilets. Both sets of toilets have disabled facilities.",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=YCw02tAz59g&communitychannel=6-11",
    "St Pancras Station,London,NW1 4QP",
    "NW1 4QP",
    "http://www.stpancras.com",
    "020 7843 4250",
    "",
  ],
  [
    "r2Sx3q6qRjk",
    "\n\n\n\nSwiss Cottage Library\n",
    "One of London's largest public libraries, run by Camden Council. Collection includes books, talking books, CDs, self-help leaflets, music scores, a special historical collection of philosophy and psychology books and a large reserve stock. Information about Council and other local services and organisations. Photocopiers and…",
    "https://cindex.camden.gov.uk/kb5/camden/cd/advice.page?id=r2Sx3q6qRjk",
    "Swiss Cottage Library,88 ,Avenue Road,London,NW3 3HA",
    "NW3 3HA",
    "http://www.camden.gov.uk/swisscottagelibrary",
    "020 7974 4444",
    "libraries@camden.gov.uk",
  ],
  [
    "dQ6qh4g32YM",
    "\nWaterlow Park Centre Public Conveniences\n",
    "",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=dQ6qh4g32YM&communitychannel=6-11",
    "Waterlow Park Centre,Dartmouth Park Hill,London,N19 5JF",
    "N19 5JF",
    "https://beta.camden.gov.uk/public-toilets",
    "020 7974 4444",
    "operationsteam@camden.gov.uk",
  ],
  [
    "nYPA8Ew6zlI",
    "\nWest End Lane Public Conveniences\n",
    "Ladies' and gents' toilets, with disabled access and baby changing facilities.",
    "https://cindex.camden.gov.uk/kb5/camden/cd/service.page?id=nYPA8Ew6zlI&communitychannel=6-11",
    "Block A,211 ,Arlington Rd,London,NW1 7HD",
    "NW1 7HD",
    "http://www.camden.gov.uk/toilets",
    "",
    "operationsteam@camden.gov.uk",
  ],
  [
    "r2Sx3q6qRjk",
    "\n\n\n\nWest Hampstead Library\n",
    "Public library run by Camden Council. Collection includes books, talking books and self help leaflets. Children's library offers Rhyme Time session for under fives Fri 11.30am-12noon, and Baby Bounce sessions for under twos Thu 11.30am-12noon (term time only) and Thu 2-2.30pm. Rhyme Time and Baby…",
    "https://cindex.camden.gov.uk/kb5/camden/cd/advice.page?id=r2Sx3q6qRjk",
    "Dennington Park Road,London,NW6 1AU",
    "NW6 1AU",
    "http://www.camden.gov.uk/westhampsteadlibrary",
    "020 7974 4444",
    "libraries@camden.gov.uk",
  ],
  [""],
];

export { testCSVData };
